# Generated by Django 5.2.17 on 2026-09-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='nom',
            field=models.CharField(max_length=130, unique=True),
        ),
    ]
