# Generated by Django 5.2.17 on 2026-10-03 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_competence_enseignantreferent_etudiant_offre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuteurEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'masculaire'), ('F', 'feminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuteur_entreprise', to='stages.entreprise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
