# Generated by Django 5.2.17 on 2026-10-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0005_tuteurentreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=250)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stage', to='stages.candidature')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.enseignantreferent')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.tuteurentreprise')),
            ],
        ),
    ]
